[project]
name = "projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arviz>=1.1.0",
    "catboost>=1.2.10",
    "causalimpact>=0.2.6",
    "doubleml>=0.11.3",
    "graphviz>=0.21",
    "highlight-text>=0.2",
    "holidays>=0.97",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.9",
    "outlier-utils>=0.0.5",
    "pymupdf>=1.27.2.3",
    "requests>=2.34.2",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "shap>=0.51.0",
    "statsmodels>=0.14.6",
]
