[project]
name = "projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "causalimpact>=0.2.6",
    "highlight-text>=0.2",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.9",
    "outlier-utils>=0.0.5",
    "requests>=2.34.2",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.6",
]
